-- =========================================================
-- Supabase PostgreSQL Schema for BodyTag
-- =========================================================

-- 1. Table: Exercises (????????????????????????????????????/???)
CREATE TABLE IF NOT EXISTS public.exercises (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    name_th TEXT,
    category TEXT NOT NULL,
    primary_muscles TEXT NOT NULL,
    secondary_muscles TEXT NOT NULL,
    is_custom INTEGER DEFAULT 0
);

-- 2. Table: Workout Weeks (??????????????????)
CREATE TABLE IF NOT EXISTS public.workout_weeks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_number INTEGER NOT NULL,
    title TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Table: Workout Days (?????????????????????????)
CREATE TABLE IF NOT EXISTS public.workout_days (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_id BIGINT REFERENCES public.workout_weeks(id) ON DELETE CASCADE NOT NULL,
    day_number INTEGER NOT NULL,
    title TEXT NOT NULL,
    real_date TEXT DEFAULT '',
    notes TEXT DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Table: Workout Logs (?????????????????????????)
CREATE TABLE IF NOT EXISTS public.workout_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_id BIGINT REFERENCES public.workout_days(id) ON DELETE CASCADE,
    exercise_id TEXT REFERENCES public.exercises(id) NOT NULL,
    sets INTEGER NOT NULL,
    reps INTEGER DEFAULT 10,
    weight REAL DEFAULT 0,
    rpe REAL DEFAULT 8.0,
    notes TEXT DEFAULT '',
    logged_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Row Level Security (RLS) & Public Policies
ALTER TABLE public.exercises ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workout_weeks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workout_days ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workout_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS Allow anon read exercises ON public.exercises;
CREATE POLICY Allow anon read exercises ON public.exercises FOR SELECT USING (true);

DROP POLICY IF EXISTS Allow anon write exercises ON public.exercises;
CREATE POLICY Allow anon write exercises ON public.exercises FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS Allow anon all workout_weeks ON public.workout_weeks;
CREATE POLICY Allow anon all workout_weeks ON public.workout_weeks FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS Allow anon all workout_days ON public.workout_days;
CREATE POLICY Allow anon all workout_days ON public.workout_days FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS Allow anon all workout_logs ON public.workout_logs;
CREATE POLICY Allow anon all workout_logs ON public.workout_logs FOR ALL USING (true) WITH CHECK (true);
